language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t emanualjade/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true emanualjade/react-test npm test

after_success:
  - docker build -t emanualjade/multi-client ./client
  - docker build -t emanualjade/multi-nginx ./nginx
  - docker build -t emanualjade/multi-server ./server
  - docker build -t emanualjade/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push emanualjade/multi-client
  - docker push emanualjade/multi-nginx
  - docker push emanualjade/multi-server
  - docker push emanualjade/multi-worker
deploy:
  provider: elasticbeanstalk
  region: us-east-1
  app: multi-docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-us-east-1-842276644773
  bucket_path: docker-multi
  on:
    brance: master
  access_key_id: 
    secure: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY
